### PR TITLE
Support for backends

### PR DESCRIPTION
**Pull request by chromano**
Hi,

I've implemented, with some help of shockflash, a basic support for backends. It enables the user to select what "upload" (storage) backend to use for saving the uploaded files.

Currently, there 3 backends available: S3 (the original), local (saves files locally) and thumbnail (save images locally, allowing re-dimensioning/cropping).

Also, the README file was updated to include information about backends.

Would you mind to merge it? Please, let me know.

Thanks
Henrique

### CODE REVIEW

**Comment by skoczen** [comment]
Hey chromano, this looks great first glance through - sorry for the slow response, github didn't notify of your pull request - didn't see it until shockflash sent me a message.

Will do a more thorough read-through this afternoon, and if all looks good, merge it in. Thanks for the contribution!

**Comment by skoczen** [comment]
I was wondering about why thumbnails got their own special-cased back end, but it ends up being a really nice example of how to subclass local for special behavior.

This all looks great - merging it in!  Will add you both to the credits shortly.

**Comment by chromano** [comment]
Cool, thanks!

The thumbnail backend I wrote for a project that I'm working on, but I thought it could be useful for others as well (submitting images with ajaxuploader is pretty cool!).

**Comment by skoczen** [comment]
I've made one backwards incompatible change - switching DIMENSION to DIMENSIONS, since it covers both height and width.

Updated the docs & fixed an S3 bug with the latest push as well. Thought I'd let you know about the backwards incompatibility though!

**Pull request merged**
