### PR TITLE
added args & kwargs to __call__ due to possible url parameter 

### PR DESCRIPTION
**Pull request by minddust**
urls like:

url(r'^album/(?P<slug>[-\w]+)/ajax-upload/$', ajax_upload,
name="ajax_upload"),

cannot be used without kwargs in **call**

### CODE REVIEW

**Comment by skoczen** [comment]
Hi there,

Maybe I'm missing something, but in the example use case you provide, isn't that captured variable being discarded?  Wouldn't you in fact want to subclass the view, and handle it properly?

To me, the way it is right now is more correct, since it fails when you pass in kwargs (since by default, the backend tosses them directly away.)

If I'm missing something, please let me know!

**Comment by minddust** [comment]
hey :) consider this:

you got a bunch of urls like this:

url(r'^album/(?P<slug>[-\w]+)/$', details, name="details"),
url(r'^album/(?P<slug>[-\w]+)/someview/$', someview, name="someview"),
url(r'^album/(?P<slug>[-\w]+)/ajax-upload/$', ajax_upload, name="ajax_upload"),

i wanna use the uploader in an url with a slug for 2 reasons.
1. avoid "possible" collision urls
2. connect with uploaded items with the album (via slug)

with the current setup it isnt possible because urls with a variable would brick the ajax uploader flow.

the pull request doesnt solve reason number 2 but avoid urls collisions and therefore the app to brick. 

it's my first day of vacation so i'm off for a week. maybe you got the time to test / take a look at the problem. thanks :)

**Comment by skoczen** [comment]
If you're on vacation, I suspect you'll have more time than me!  That's when I actually get most of my time to hack on improvements to this stuff.

I get what you're saying with #1 - but it "solves" the problem by implying that it behaves in a way it doesn't.

Here's what I'd love to see as a pull that would solve this - _proper_ passthrough of _args and *_kwargs all the way through the backend (calls, _ajax_upload, etc).  That would fix your #1, and provide the facilities you'd need to properly implement #2. 

If you've got time to do that, that'd be kick-ass.

**Comment by minddust** [comment]
vacation at the beach ;-) yeah.. thought about that, but didn't had the time. but you are definitely right. next pull is coming this days. best stephan

**Comment by minddust** [comment]
sorry - got many other things on my list. but... finally finish this :D

**Comment by skoczen** [comment]
Looks great!  Merging in, will push a new version to pypi shortly.

**Pull request merged**
