### PR TITLE
Using Python 2.6's json for Django 1.5 compatibility

### PR DESCRIPTION
**Pull request by bvallant**
Using simplejson breaks with Django 1.5+. Using Python 2.6's `json`

### CODE REVIEW

**Comment by olexiystrashko** [comment]
+1 for this fix. I have "**init**() got an unexpected keyword argument 'namedtuple_as_object'" when uploading on Django 1.5 / Python 2.7.

**Comment by rsenkbeil** [comment]
:thumbsup: I'm having the same problem as @olexiystrashko.

**Comment by ribalba** [comment]
Same issue here. Please patch.

**Comment by applecat** [comment]
+1, I have the same issue. Fix this plese...

**Comment by skoczen** [comment]
Apologies for the delay, all, life's been crazy.  Would have already been merged if it was a clean patch - will aim to get this in today!

**Comment by skoczen** [comment]
Released, up at pypi as 0.3.1!

**Pull request closed without merging**
