### PR TITLE
Created a base class that doesn't return an HttpResponse object

### PR DESCRIPTION
**Pull request by boosh**
I've created a new class called RawAjaxFileUploader which just performs the upload and returns the response dictionary to the client code. This allows extra server-side processing (such as saving the path the uploaded file in the database).

AjaxFileUploader is a subclass of this class which behaves exactly as it used to, returning the response serialised and wrapped in an HttpResponse object.

### CODE REVIEW

**Comment by skoczen** [comment]
Hey Boosh,

I'm not against this pull request, but it does raise some questions for me.  Can you toss some more info my way?

What's the use-case here, instead of overriding `upload_complete` in the backend?

I'm wary of providing too many ways to do the same thing - and though I see the logic in what you're doing, it's still tightly coupled to the JS - which expects a HttpResponse.  I'm missing some useful case that you clearly have.

A couple other minor points:
-  `Raw` isn't my favorite name.  Base would be better (though it duplicates the Base backend, and creates confusion), or something that indicates that it returns a dict. I'm open to suggestions - `Raw` just states that it's a stripped down version of something, and as a new user, I have no idea what.
-  Please add yourself to the AUTHORS file with your pull, attributed how you'd like!

Thanks for contributing!

**Comment by boosh** [comment]
Hi,

This makes it more modular, by allowing the backend to be responsible purely for storage and the view to handle business logic, such as any pre- or post-processing that may be required. 

In my case, I'm scaling images. So I've written a custom backend to scale the uploaded image to multiple different sets of dimensions, and I need to update my model to save the file name. I could put this in a backend, but I want to isolate this functionality. I'll use the same handler for this 'vanilla' upload and scaling, and later add a way of allowing users to crop the uploaded image (similar to how you select your face for your profile image on facebook).

The view does still need to return the JSON as an HttpResponse - this now allows me to do pre-/post-processing around the ajax uploader instead of having it as a single black box.

As for the name - I'm OK with `Base`, and I'm fine without being added to AUTHORS. 

Thanks for your work!

**Comment by skoczen** [comment]
Hey,

I think I'd still put your image-scaling code in the upload_complete hook. That's what it's really there for (cropping images is actually one of the examples.)

However, in this case, I think that really comes down to coding style. You make a fair case, and I'm happy to take the merge.  However, for consistency and attempting to have one clear way to do things, I'm not going to add it to the docs.  If folks are looking to implement something in the same style, they'll be happy to find your abstracted backend there.

If you don't mind making the change to `Base`, I'll merge it in right away!

Thanks,
Steven

**Comment by boosh** [comment]
OK done - but I just updated the docs before I saw this ticket :-(

**Comment by skoczen** [comment]
Doing a catch-up clean-out of issues on ajaxuploader.  Looks like this one stalled, so I'm closing it. Please re-open if that's not right!

**Pull request closed without merging**
